add_library(ulib
	NSArray+ulib.m
	NSData+ulib.m
	NSDate+ulib.m
	NSDictionary+ulib.m
	NSMutableArray+ulib.m
	NSMutableData+ulib.m
	NSMutableString+ulib.m
	NSNumber+ulib.m
	NSObject+ulib.m
	NSString+ulib.m
	ulib.m
	UMASN1BitString.m
	UMASN1Boolean.m
	UMASN1Choice.m
	UMASN1EndOfContents.m
	UMASN1Enumerated.m
	UMASN1Integer.m
	UMASN1Length.m
	UMASN1NamedList.m
	UMASN1Null.m
	UMASN1Object.m
	UMASN1ObjectConstructed.m
	UMASN1ObjectDescriptor.m
	UMASN1ObjectIdentifier.m
	UMASN1ObjectPrimitive.m
	UMASN1OctetString.m
	UMASN1Real.m
	UMASN1Sequence.m
	UMASN1Set.m
	UMASN1Tag.m
	UMASN1UTF8String.m
	UMAtomicCounter.m
	UMAtomicDate.m
	UMAverageDelay.m
	UMBackgrounder.m
	UMBackgrounderWithQueue.m
	UMBackgrounderWithQueues.m
	UMCommandLine.m
	UMConfig.m
	UMConfigGroup.m
	UMConfigParsedLine.m
	UMConstantStringsDict.m
	UMCountryCodePrefixDigitTree.m
	UMCountryDigitTree.m
	UMCrypto.m
	UMDataWithHistory.m
	UMDateTimeStuff.m
	UMDateWithHistory.m
	UMDigitTree.m
	UMDigitTreeEntry.m
	UMDirtyBoolean.m
	UMDirtyData.m
	UMDirtyDate.m
	UMDirtyDouble.m
	UMDirtyInteger.m
	UMDirtyObject.m
	UMDirtyString.m
	UMDoubleWithHistory.m
	UMFileTracker.m
	UMFileTrackingInfo.m
	UMHistoryLog.m
	UMHistoryLogEntry.m
	UMHost.m
	UMHTTP2Connection.m
	UMHTTP2Frame.m
	UMHTTP2Server.m
	UMHTTP2Session.m
	UMHTTPClient.m
	UMHTTPClientRequest.m
	UMHTTPConnection.m
	UMHTTPCookie.m
	UMHTTPPageCache.m
	UMHTTPPageHandler.m
	UMHTTPPageRef.m
	UMHTTPRequest.m
	UMHTTPServer.m
	UMHTTPSServer.m
	UMHTTPTask_ReadRequest.m
	UMHTTPURLHandler.m
	UMHTTPWebSocketFrame.m
	UMIntegerWithHistory.m
	UMIPAddressList.m
	UMIPAddressListEntry.m
	UMJsonParser.m
	UMJsonStreamParser.m
	UMJsonStreamParserAccumulator.m
	UMJsonStreamParserAdapter.m
	UMJsonStreamParserState.m
	UMJsonStreamWriter.m
	UMJsonStreamWriterAccumulator.m
	UMJsonStreamWriterState.m
	UMJsonTokeniser.m
	UMJsonUTF8Stream.m
	UMJsonWriter.m
	UMKeypair.m
	UMLayer.m
	UMLayerTask.m
	UMLogBuffered.m
	UMLogConsole.m
	UMLogDestination.m
	UMLogEntry.m
	UMLogFeed.m
	UMLogFile.m
	UMLogHandler.m
	UMLogLevel.m
	UMMemoryHeader.m
	UMMicroSec.m
	UMMutex.m
	UMNamedList.m
	UMObject.m
	UMObjectStatistic.m
	UMObjectStatisticEntry.m
	UMObjectTree.m
	UMObjectTreeEntry.m
	UMObjectWithHistory.m
	UMPacket.m
	UMPKI.m
	UMPlugin.m
	UMPluginDirectory.m
	UMPluginHandler.m
	UMPool.m
	UMPrivateKey.m
	UMPrometheus.m
	UMPrometheusMetric.m
	UMPrometheusMetricUptime.m
	UMPrometheusThroughputMetric.m
	UMProtocolBuffer.m
	UMPublicKey.m
	UMQueueMulti.m
	UMQueueNull.m
	UMQueueSingle.m
	UMRedisCommand.m
	UMRedisSession.m
	UMRedisStatus.m
	UMRegex.m
	UMRegexMatch.m
	UMRpcClient.m
	UMRpcCommandHandler.m
	UMRpcHandler.m
	UMRpcMessage_GenericError.m
	UMRpcMessage_HeartbeatRequest.m
	UMRpcMessage_HeartbeatResponse.m
	UMRpcMessage_LoginRequest.m
	UMRpcMessage_LoginResponse.m
	UMRpcMessage_LogoutRequest.m
	UMRpcMessage_LogoutResponse.m
	UMRpcMessage_TestRequest.m
	UMRpcMessage_TestResponse.m
	UMRpcMessage.m
	UMRpcMessageDecoder.m
	UMRpcServer.m
	UMRpcSession.m
	UMRpcSessionHandler.m
	UMScanner.m
	UMScannerChar.m
	UMSerialPort.m
	UMSleeper.m
	UMSocket.m
	UMSSLCertificate.m
	UMStatistic.m
	UMStatisticEntry.m
	UMStdIo.m
	UMStringWithHistory.m
	UMSynchronizedArray.m
	UMSynchronizedDictionary.m
	UMSynchronizedSortedDictionary.m
	UMSyntaxAction.m
	UMSyntaxContext.m
	UMSyntaxToken_Const.m
	UMSyntaxToken_Digits.m
	UMSyntaxToken_Name.m
	UMSyntaxToken_Number.m
	UMSyntaxToken.m
	UMSyslogClient.m
	UMTaskQueue.m
	UMTaskQueueMulti.m
	UMTaskQueueTask.m
	UMThreadHelpers.m
	UMThroughputCounter.m
	UMTimer.m
	UMTimerBackgrounder.m
	UMTokenizer.m
	UMTokenizerWord.m
	UMUtil.m
	UMUUID.m
	UMZMQSocket.m
	UMZMQSocket+ASN1.m
)